# Generated by Django 3.1.2 on 2023-12-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_inscripcion_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechapostulacion', models.DateField()),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('nombretaller', models.CharField(max_length=30)),
                ('fecharesultado', models.DateField(blank=True, null=True)),
                ('adultomayor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.adultomayor')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instructor')),
            ],
        ),
    ]
