# Generated by Django 3.1.2 on 2023-11-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_municipalidad_sala_taller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.taller')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.adulto')),
            ],
        ),
    ]
