# Generated by Django 3.1.2 on 2023-11-26 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_adulto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipalidad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSala', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('municipalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipalidad')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
            ],
        ),
    ]
